### ISSUE TITLE
Hide menu items if they have a membership

### ISSUE THREAD

**Issue by seb86** [helgatheviking/nav-menu-roles-woocommerce-memberships#2]
It would be great if menu items that need to show for everyone (logged in and out) but then hide if the logged in user has a minimum membership.

Could this be done?

**Comment by helgatheviking** [comment]
Hiding by minimum role isn't included in Nav Menu Roles and I don't expect to be adding it. However, NMR is pretty extensible and you could add that feature to it. See: https://github.com/helgatheviking/nav-menu-roles#adding-a-new-role
