### ISSUE TITLE
Duplicate fields displayed

### ISSUE THREAD

**Issue by notnacfed** [helgatheviking/nav-menu-roles-woocommerce-memberships#3]
Hello and thanks for plugin. I try to install and use but same to be not working correct. 

I see on backend pat to choose type of Membership but also a second part to choose with type of role. Is possibile to fix it?
![menu  wordpress](https://user-images.githubusercontent.com/46137383/51850961-2d290000-2323-11e9-8187-4f7c4496c6d9.png)

**Comment by helgatheviking** [comment]
Hi, this plugin is not _actively_ maintained and is provided _as is_. That said, I'm fairly confident that the drop-down select element (that reads "Utenti connessi") and everything below that is coming from a plugin other than Nav Menu Roles, WooCommerce Memberships, or this bridge plugin. I'd test disabling your other plugins one at a time. Also, check your theme.

**Comment by notnacfed** [comment]
Hello, thanks a lot, there was a conflict with other plugin.

I need to have a custom redirect (to a custom page) for each different type of membership. Have you have any idea or notice to do that? 

Thanks

**Comment by helgatheviking** [comment]
Hi, that's not really related to Nav Menu Roles in any way. But, if you mean redirect users on login you could try filtering [`login_redirect`](https://codex.wordpress.org/Plugin_API/Filter_Reference/login_redirect) or a plugin like [Peter's Login Redirect](https://wordpress.org/plugins/peters-login-redirect/).
