### ISSUE TITLE
Free Trial status not showing the button until change to active status

### ISSUE THREAD

**Issue by savvas80** [helgatheviking/nav-menu-roles-woocommerce-memberships#4]
Hi there !
Congrats for that plugin .
It works fine and is the core of functionality of my members.
In the trial subscriptions i have and membership plans when customer pay , the menu button is not showing as i want in free trial status .
What i have to do please ?

**Comment by helgatheviking** [comment]
Have you assigned the correct role to the trial user? is that the same role you are applying to the menu item?
